### PR TITLE
Relax python dep for HA 2023.5

### PR DESCRIPTION
**Pull request by drc38**
NB httpx constraints need to be relaxed too. Not sure why dependabot hasn't already created PR?

### CODE REVIEW

**Comment by drc38** [comment]
@hardbyte Hi Brian, I've added in the relaxing of the httpx constraint appreciate if you are able to merge and release a new version. Thanks!

**Review by hardbyte — APPROVED** [review]
Ta, will cut a release!

**Comment by hardbyte** [comment]
Eek, something in this has upset poetry installing dependencies.

**Comment by drc38** [comment]
Maybe the python one? The httpx change worked on one of my repos.

**Comment by hardbyte** [comment]
Yeah I reproduced locally - seems like pycognito supports hundreds or even thousands of different versions of boto3 and poetry likes to look at them all.

**Comment by drc38** [comment]
Ah ok so poetry error unrelated to this PR per se

**Comment by hardbyte** [comment]
Yeah, sorry I wasn't pointing fingers! All fixed and re-released.

Thanks for the update

**Comment by drc38** [comment]
No worries, always a bit odd when something fails but it is unrelated to the PR change. Just wanted to clarify.

**Pull request merged**
